FROM prux-bin
 
#
# Copy the bitcoin.conf file from
# the build context into the container
#
RUN mkdir -p /root/.prux
COPY prux.conf /root/.prux/prux.conf

#
# Expose the port for the RPC interface
#
EXPOSE 9595/tcp
 
#
# Start the prux server
#
ENTRYPOINT ["/usr/local/bin/pruxd && RUN service tor start "]
CMD ["-conf=/root/.prux/prux.conf", "-server=1", "-printtoconsole", "-txindex=1"]


